{% set version = "1.7.11" %}

package:
  name: dicttoxml
  version: {{ version }}

source:
  fn: dicttoxml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dicttoxml/dicttoxml-{{ version }}.tar.gz
  sha256: 18894c2d87373bce13729580de638a39fabd619219bccd8d85cde3744de45273

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - dicttoxml

about:
  home: https://github.com/quandyfactory/dicttoxml
  license: GPL-2.0-only
  summary: Converts a Python dictionary or other native data type into a valid XML string.
  license_family: GPL
  license_file: LICENSE.txt
  dev_url: https://github.com/quandyfactory/dicttoxml
  doc_url: https://github.com/quandyfactory/dicttoxml

extra:
  recipe-maintainers:
    - johanneskoester
    - jan-janssen
