{% set version = "1.7.8" %}

package:
  name: dicttoxml
  version: {{ version }}

source:
  fn: dicttoxml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dicttoxml/dicttoxml-{{ version }}.tar.gz
  sha256: 78e6f2d4f655fa21ea70421a6f6c1291e45b531f195c5b389cf72161fd2a865f
  patches:
    - collections.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - dicttoxml

about:
  home: https://github.com/quandyfactory/dicttoxml
  license: GPL-2.0
  summary: 'Converts a Python dictionary or other native data type into a valid XML string. '
  license_family: GPL
  license_file: LICENCE.txt
  dev_url: https://github.com/quandyfactory/dicttoxml
  doc_url: https://github.com/quandyfactory/dicttoxml

extra:
  recipe-maintainers:
    - johanneskoester
    - jan-janssen
