{% set version = "1.7.13" %}

package:
  name: dicttoxml
  version: {{ version }}

source:
  fn: dicttoxml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dicttoxml/dicttoxml-{{ version }}.tar.gz
  sha256: e564ab24916c6ac3c25d4d672482c0a1bb4eb0f084c680b64d197f400f0e2168

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - dicttoxml

about:
  home: https://github.com/quandyfactory/dicttoxml
  license: GPL-2.0-only
  summary: Converts a Python dictionary or other native data type into a valid XML string.
  license_family: GPL
  license_file: LICENCE.txt
  dev_url: https://github.com/quandyfactory/dicttoxml
  doc_url: https://github.com/quandyfactory/dicttoxml

extra:
  recipe-maintainers:
    - johanneskoester
    - jan-janssen
